# Generated by Django 5.1.4 on 2025-01-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
                ('itemcolor', models.CharField(max_length=15)),
                ('itemprice', models.CharField(max_length=20)),
            ],
        ),
    ]
